server:
  port: 8761 # port on which eureka server will be available

spring:
  application:
    name: netflix-eureka-server # name of eureka server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
