server:
  port: 8085 # port at which the service will be available
spring:
  application:
    name: address-service

info: # basic application info to be made available under /info
  app:
    name: address-service
    description: Service to provide user's address
    version: 1.0.0

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true